/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "hqpeguzlymjvaojyhcef"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxcGVndXpseW1qdmFvanloY2VmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE2MjQ4NzcsImV4cCI6MjA5NzIwMDg3N30.xfgw0RiioTs2v8Wey-w3JG-6LFJA7hbe1CoqsOd4qaA"